![imagen](./img/ejercicios.png)

## Ejercicio 1
Importa el módulo de `numpy` y obtén su versión.

In [2]:
import numpy as np

In [3]:
np.version

<module 'numpy.version' from 'c:\\Users\\Victor\\miniconda3\\envs\\EVA_ENV\\lib\\site-packages\\numpy\\version.py'>

## Ejercicio 2
Crea un array de una dimensión que vaya de 0 a 9. Llamalo `my_array`

In [4]:
my_array = np.array([1,2,3,4,5,6,7,8,9])
print(my_array)
type(my_array)

[1 2 3 4 5 6 7 8 9]


numpy.ndarray

In [5]:
my_array2 = np.arange(10)
my_array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Ejercicio 3
Crea un array 3x3, que sea todo a True

In [6]:
todo_true = np.full((3,3),"True")
todo_true

array([['True', 'True', 'True'],
       ['True', 'True', 'True'],
       ['True', 'True', 'True']], dtype='<U4')

In [7]:
np.array([1,2,3],[4,5,6],[7,8,9])

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

## Ejercicio 4
Extrae todos los impares de `my_array`

In [8]:
mask = (my_array%2==1)
my_array[mask]

array([1, 3, 5, 7, 9])

## Ejercicio 5
En un nuevo array, sustituye todos los impares de `my_array` por -1

In [9]:
my_array_5 = np.arange(10)
my_array_5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
mask = (my_array_5%2==1)
my_array_5[mask]= -1
my_array_5

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

## Ejercicio 6
En un nuevo array, sustituye todos los impares de `my_array` por -1. Esta vez usa `where`

In [11]:
my_array_6 = np.arange(10)
print(np.where(my_array_6%2==1,-1,my_array_6))
# llamando a la función where, indicamos que es lo que queremos que pase con los elementos que cumplan la función, y con el resto

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


## Ejercicio 7
Convierte `my_array` en un nuevo array de dos dimensiones mediante `reshape`.

In [12]:
my_array_5.reshape((2,5)) # con los paréntesis decidimos la cantidad de dimensiones, y con los numeros de dentro, cuantas filas de cuantos elementos (columnas) queremos

array([[ 0, -1,  2, -1,  4],
       [-1,  6, -1,  8, -1]])

## Ejercicio 8
Concatena los siguientes arrays verticamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [13]:
a = np.arange(10).reshape(2,-1)
print(a)
b = np.repeat(1, 10).reshape(2,-1)
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


In [14]:
np.concatenate([a,b],axis = 0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Ejercicio 9
Concatena los siguientes arrays horizontamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [15]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.concatenate([a,b], axis = 1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Ejercicio 10
Encuentra todos los elementos en común entre ambos arrays. [Para ello usa el método `intersect1d`](https://numpy.org/doc/stable/reference/generated/numpy.intersect1d.html)

```Python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

In [16]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d([a],[b])

array([2, 4])

## Ejercicio 11
Obtén la documentación acerca de la función `concatenate`

In [17]:
np.concatenate.__doc__

'\n    concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")\n\n    Join a sequence of arrays along an existing axis.\n\n    Parameters\n    ----------\n    a1, a2, ... : sequence of array_like\n        The arrays must have the same shape, except in the dimension\n        corresponding to `axis` (the first, by default).\n    axis : int, optional\n        The axis along which the arrays will be joined.  If axis is None,\n        arrays are flattened before use.  Default is 0.\n    out : ndarray, optional\n        If provided, the destination to place the result. The shape must be\n        correct, matching that of what concatenate would have returned if no\n        out argument were specified.\n    dtype : str or dtype\n        If provided, the destination array will have this dtype. Cannot be\n        provided together with `out`.\n\n        .. versionadded:: 1.20.0\n\n    casting : {\'no\', \'equiv\', \'safe\', \'same_kind\', \'unsafe\'}, optional\n        Cont

## Ejercicio 12
Crea un array unidimensional que vaya del 0 al 9. Llámalo `my_array`. 
1. Multiplica cada uno de los elementos de `my_array` por 10, en un nuevo array
2. Accede al primer elemento del array
3. Accede al último elemento del array
4. Imprime por pantalla los numeros del 1 al 7

In [18]:
my_array = np.arange(10)
my_array_10 = my_array*10
print(my_array_10)
print(my_array[0])
print(my_array[-1])
print(my_array[1:8])

[ 0 10 20 30 40 50 60 70 80 90]
0
9
[1 2 3 4 5 6 7]


## Ejercicio 13
Crea un array manualmente de tres filas por tres columnas. Llámalo `my_matrix`

In [19]:
my_matrix = ([1,2,3],
             [4,5,6],
             [7,8,9])

## Ejercicio 14
Obtén la siguiente secuencia:

```Python
[ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49]
```

In [20]:
my_array_14 = np.arange(1,50,3)
my_array_14

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])

## Ejercicio 15
Obtén la siguiente secuencia

```Python
[4., 3.75, 3.5 , 3.25, 3.  , 2.75, 2.5 , 2.25, 2., 1.75, 1.5 ,1.25]
```

In [21]:
my_array_15 = np.arange(4,1,-0.25)

my_array_15

array([4.  , 3.75, 3.5 , 3.25, 3.  , 2.75, 2.5 , 2.25, 2.  , 1.75, 1.5 ,
       1.25])

## Ejercicio 16
Lee la imagen "numpy.png"

![imagen](./img/numpy.png)

## Ejercicio 17
Crea un array de 4x1. A continuación convierte el array a un 2x2

In [22]:
my_array_17 = np.full([4,1],5)
my_array_17_1 = np.reshape(my_array_17,(2,2))
my_array_17, my_array_17_1

(array([[5],
        [5],
        [5],
        [5]]),
 array([[5, 5],
        [5, 5]]))

## Ejercicio 18
Crea una secuencia aleatoria. La secuencia se tiene que componer de 4 matrices de 5x3. Serían 3 dimensiones diferentes.

In [23]:
np.random.randint(0,10, size=(4,5,3))

array([[[1, 2, 7],
        [6, 2, 5],
        [9, 1, 7],
        [6, 5, 9],
        [9, 8, 3]],

       [[6, 7, 0],
        [7, 5, 2],
        [0, 3, 4],
        [7, 1, 7],
        [3, 4, 6]],

       [[3, 1, 2],
        [6, 5, 2],
        [2, 0, 7],
        [2, 7, 2],
        [4, 6, 3]],

       [[5, 7, 0],
        [6, 3, 3],
        [2, 6, 9],
        [3, 1, 1],
        [3, 4, 5]]])

## Ejercicio 19
Crea una matriz de 10x1, toda ella compuesta por `False`. Después transformalo en un 2x5

In [24]:
my_array_19 = np.full([10,1],False)
my_array_19

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False]])

In [25]:
np.reshape(my_array_19,(2,5))

array([[False, False, False, False, False],
       [False, False, False, False, False]])

## Ejercicio 20
Dado el siguiente array

```Python
x =np.random.randint(10, 20, size = (5,2,6))
```

1. ¿Cuántos elementos tiene el array? 60
2. ¿Cuántas dimensiones?3
3. ¿Cuántos elementos tiene cada dimensión? Dimensión 1: 1 elemento // dimensión 2: 10 elementos //dimensión 3: 60 elementos

In [26]:
x =np.random.randint(10, 20, size = (5,2,6))
x

array([[[12, 16, 12, 14, 10, 16],
        [18, 13, 11, 15, 12, 12]],

       [[16, 16, 14, 15, 11, 19],
        [11, 16, 11, 14, 13, 19]],

       [[12, 15, 16, 14, 14, 12],
        [10, 11, 17, 11, 12, 10]],

       [[10, 11, 15, 15, 13, 12],
        [15, 18, 15, 15, 15, 19]],

       [[13, 17, 14, 13, 12, 19],
        [10, 10, 19, 12, 17, 13]]])

In [27]:
x.ndim

3

In [28]:
x.size

60

In [29]:
x.shape

(5, 2, 6)