![imagen](./img/ejercicios.png)

In [2]:
import numpy as np

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [7]:
my_array = np.arange(0,10)

my_array1 = np.where(my_array%2==1)

my_array1_1 = np.flip(my_array1)
my_array1_1


array([[9, 7, 5, 3, 1]], dtype=int64)

## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [8]:
my_array_2 = np.flip(my_array)
my_array_2[1:3]

array([8, 7])

## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [13]:
my_array_3 = np.flip(my_array)
my_array_3[-3:]

array([2, 1, 0])

## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [22]:
my_array_4 = np.arange(20)+1
my_array_4_1 = np.reshape(my_array_4,(4,5))
my_array_4_1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [32]:
my_array_5 = my_array_4_1
my_array_5[:2, :2]

array([[ 1,  2],
       [ 6,  7],
       [11, 12]])

## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [57]:
my_array_5[::2, ::2]

array([[ 1,  3,  5],
       [11, 13, 15]])

## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [36]:
my_array_7 = my_array_5[::,::-1]
my_array_7[:3,:6]

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])

## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [ ]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

In [45]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
np.where(x!="Loro","",x)


array(['Loro', '', '', 'Loro', ''], dtype='<U5')

In [46]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
x[(x=="Loro")]

array(['Loro', 'Loro'], dtype='<U5')

## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [48]:
my_array_9 = np.arange(20)
np.reshape(my_array_9,(2,5,2))

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [53]:
my_array_5[::-1,::-1]

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [64]:
my_array_11 = np.full((0,10),0)

np.nbytes[my_array_11]

4

## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [72]:
my_array_12 = np.arange(10,50)
print(my_array_12)
np.flip(my_array_12)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [75]:
my_array_13 = ([1,2,0,0,4,0])
np.nonzero(my_array_13)

(array([0, 1, 4], dtype=int64),)

## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [94]:
my_array_14 = np.random.randint(0,10, size = (10,10))
print(np.min(my_array_14))
print(np.max(my_array_14))



0
9


## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [97]:
my_array_15 = np.random.randint(10,size= (1,30))
np.median(my_array_15)

6.0

## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quiras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [145]:
my_array_16 = np.full((10,10),0)
my_array_16[:1]=1
my_array_16[-1]=1
my_array_16[1:,0:1]=1
my_array_16[:9,9:]=1
my_array_16


array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

## Ejercicio 17
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [ ]:
"""x[inicio_filas: final_filas:pasos_filas,inicio_columnas:final_columnas:pasos_columnas]"""

In [21]:
my_array_17 = np.full((8,8),1)
my_array_17[0:-1:2,0:-1:2]=0
my_array_17[1:8:2,1:8:2]=0
my_array_17

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [22]:
my_array_25 = np.full((10,10), 0)
my_array_25[0::2,1::2]=1
my_array_25[1::2,0::2]=1
my_array_25



array([[0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0]])

## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [27]:
my_array_18 = ([0,1])
my_array_18_1 = np.tile(my_array_18,(8,4))# FILAS COLUMNAS COÑO!
my_array_18_1

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1]])

## Ejercicio 19
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [31]:
my_array_19 = np.random.randint(0,10,(5,5))
my_array_19_med = my_array_19-(np.mean(my_array_19))
my_array_19_norm = my_array_19_med/np.std(my_array_19)
my_array_19_norm

array([[ 0.87082768,  0.87082768, -0.2552426 , -1.75666963,  0.12011416],
       [-0.63059935, -0.2552426 ,  1.6215412 , -1.75666963, -0.63059935],
       [ 1.6215412 ,  0.49547092,  0.49547092, -0.2552426 , -1.00595611],
       [ 0.87082768,  1.6215412 , -1.38131287,  0.12011416, -0.2552426 ],
       [-0.63059935, -1.38131287,  0.49547092,  1.24618444, -0.2552426 ]])

## Ejercicio 20
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [41]:
my_array_20 = np.arange(11)
my_array_20[3:9]= -1
my_array_20

array([ 0,  1,  2, -1, -1, -1, -1, -1, -1,  9, 10])

In [42]:
my_array_20_1 = np.arange(11)
my_array_20_2 = my_array_20_1*(-1)
my_array_20_2

array([  0,  -1,  -2,  -3,  -4,  -5,  -6,  -7,  -8,  -9, -10])

## Ejercicio 21
#### Bonus track. Mini hundir la flota
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**TIP apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.

In [62]:

tablero = np.full((10,10), " ")
barco1 = tablero[:2,1:2]="O"
barco2 = tablero[1:2,3:7]="O"
disparo1 = tablero[1:2,4:5]="X"
disparo2 = tablero[3:4,5:6]= "-"

tablero

array([[' ', 'O', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', 'O', ' ', 'O', 'X', 'O', 'O', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', '-', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']], dtype='<U1')

In [65]:
tablero = np.full((10,10), " ")
size = 4

if np.random.randint(0,2,1):
    orientacion = "horizontal"
    coord1 = np.random.randint(0,10)
    coord2 = np.random.randint(0,10-size+1)

    if "B" in tablero[coord1, coord2:coord2+size]:
        pass
    else: 
        tablero[coord1, coord2:coord2+size] = "B"
        n_barcos -= 1
else:
    orientacion = "vertical"

    coord1 = np.random.randint(0,10-size+1)
    coord2 = np.random.randint(0,10)

    if "B" in tablero[coord1:coord1+size, coord2]:
        pass
    else: 
        tablero[coord1:coord1+size, coord2] = "B"
tablero

array([[' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'B', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'B', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'B', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'B', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']], dtype='<U1')